config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: "gifts#index"
  resources :events do
    resources :wishlistgifts, only: %i[index create show]
  end
  resources :wishlistgifts, only: %i[] do
    resources :votings, only: %i[create show]
  end
  resources :votings, only: %i[destroy]
  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end
  resources :gifts
  get "/profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :event
  has_many :messages
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    @event = Event.new
    @chatrooms = Chatroom.joins(event: :members).where(members: { user: current_user })
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/views/chatrooms/index.html.erb
<%= render "shared/chatheader" %>
<div class="container">


  <div class="chatroombox">
    <% @chatrooms.uniq.each do |chatroom| %>

    <div class="chat">
      <%= link_to chatroom_path(chatroom) do %>

        <div class="chatinfo">
        <% if chatroom.event.photo.attached? %>
          <%= cl_image_tag chatroom.event.photo.key %>
        <% else %>
          <%=  image_tag("event.jpg", class: "") %>
        <% end %>


          <div class="chattext">
            <p><%= chatroom.name.capitalize %></p>
            <p><%= chatroom.event.start_time.strftime("%A, %d %b %Y") %></p>
          </div>

        </div>
      <% end %>
    </div>
    <% end %>

  </div>


</div>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
  data-controller="chatroom-subscription"
  data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
  data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
  <h1 class="text-center"><%= @chatroom.name.capitalize %></h1>

<div class="messages" data-chatroom-subscription-target="messages">
  <% @chatroom.messages.each do |message| %>
  <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
    <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
    <%= render "messages/message", message: message %>
    </div>
  </div>
  <% end %>
</div>

  <%= simple_form_for [@chatroom, @message],
   html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" }, class: "d-flex" } do |f| %>
  <%= f.input :content,
    label: false,
    placeholder: "Write a message...",
    wrapper_html: {class: "flex-grow-1 chatroom-input"}
  %>
  <%= f.submit "Send", class: "btn-giftit-small mb-3" %>
<% end %>
</div>