config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: "gifts#index"
  resources :events do
    resources :wishlistgifts, only: %i[index create show]
  end
  resources :wishlistgifts, only: %i[] do
    resources :votings, only: %i[create show]
  end
  resources :votings, only: %i[destroy]
  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end
  resources :gifts
  get "/profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_calendar.html.erb
<div class="calendar text-center">
  <%= month_calendar(events: @events) do |date, events| %>
    <% event = @events.where("start_time > ? AND start_time < ?", date, date + 1.day ).first %>
    <% if event  %>
      <%= link_to date.day, event_path(event), class:"round-date"%>
    <% else %>
      <%= date.day %>
    <% end %>
  <% end %>
</div>

app/views/shared/_chatheader.html.erb
<div class="giftheader">
  <h4>Events chat</h4>
</div>

app/views/shared/_createevent.html.erb
<div class="giftheader">
  <h4>Create event</h4>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fixed-bottom">
    <%= active_link_to gifts_path, active: :inclusive do %>
      <div class="container">
        <div class="footer-box">
          <%= image_tag "home.svg" %>
          <p>Home</p>
        </div>
      </div>
    <% end %>
    <%= active_link_to new_event_path, active: :exclusive do %>
      <div class="container">
        <div class="footer-box">
          <%= image_tag "gift.svg" %>
          <p>Gift</p>
        </div>
      </div>
    <% end %>
    <%= active_link_to chatrooms_path,active: :exclusive do %>
      <div class="container">
        <div class="footer-box">
          <%= image_tag "chat.svg" %>
          <p>Chat</p>
        </div>
      </div>
    <% end %>
    <%= active_link_to events_path, active: :exclusive do %>
      <div class="container">
        <div class="footer-box">
          <%= image_tag "calendar.svg" %>
          <p>Calendar</p>
        </div>
      </div>
    <% end %>
</footer>

app/views/shared/_giftheader.html.erb
<div class="giftheader">
  <h4>Calendar</h4>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top giftnavbar">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "home.svg" %>
    <% end %>

    <%= link_to events_path do %>
      <%= image_tag "giftit.svg" %>
    <% end %>

    <div class="" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="dropdown">
            <%= image_tag "https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to current_user.username, "/profile", class: "dropdown-item sharebtn" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_profilenavbar.html.erb
<div class="giftheader-profile">
    <div>
      <%= link_to gifts_path do %>
        <%= image_tag "close.svg" %>
      <% end %>
    </div>
    <h4 class="m-0 profile-header">Profile</h4>
    <div class="icons">
      <%= link_to '#' do %>
        <%= image_tag "edit.svg" %>
      <% end %>
      <%= link_to '#' do %>
        <%= image_tag "settings.svg" %>
      <% end %>
  </div>
</div>

app/views/shared/_starlink.html.erb
<div data-controller="toggle-stars", data-toggle-stars-star-token-value="<%= form_authenticity_token %>">
  <% if vote.present? %>
    <%= link_to voting_path(vote), data: { turbo_method: "delete", toggle_stars_target: "star", action: "click->toggle-stars#deleteStar" } do %>
      <%= image_tag "starfilled.svg", class:"wishlistgift-image" %>
    <% end %>
  <% else %>
    <%= link_to wishlistgift_votings_path(wishlist), data: { turbo_method: "post", toggle_stars_target: "star",  action: "click->toggle-stars#createStar" } do %>
      <%= image_tag "star.svg", class:"wishlistgift-image" %>
    <% end %>
  <% end %>
  <%= link_to event_wishlistgift_path(event, wishlist) do %>
    <div class="wishlist-item">
      <%= image_tag wishlist.gift.photo %>
      <div class="wishlist-text">
        <p><%= wishlist.gift.name.first(20) %> </p>
        <p class="wishlist-price">$<%= wishlist.gift.price.to_i %></p>
      </div>
    </div>
  <% end %>
  <% if wishlist.votings.count == 1 %>
    <p class="wishlist-votes"><%= wishlist.votings.count %> vote</p>
  <% else %>
    <p class="wishlist-votes"><%= wishlist.votings.count %> votes</p>
  <% end %>
</div>

app/views/shared/_wishlist.html.erb
<div>

  <% if gift.present? %>
    <%= link_to event_wishlistgifts_path(event, gift_params: gift.id), data: {savegifts_target: "remove", action: "click->savegifts#createWishlist"} do %>
      <%= image_tag "heart.svg", class:"wishlistgift-image" %>
    <% end %>
  <% end %>
</div>

    <%#= link_to event_path(event, :gift_params => gift.id), data: {turbo_method: "post", savegifts_target: "remove", action: "click->savegifts#createWishlist"} do %>
      <%#= image_tag "heart.svg", class:"wishlistgift-image" %>
    <%# end %>
    <%#= link_to event_path(event, :gift_params => gift.id), data: {turbo_method: "delete", savegifts_target: "remove", action: "click->savegifts#deleteWishlist"} do %>
      <%#= image_tag "heart.svg", class:"wishlistgift-image" %>
    <%# end %>

    <%#= link_to event_wishlistgifts_path(@event, :gift_params => @gift.id), data: {turbo_method: "post", action: "click->savegifts#createWishlist"} do %>
      <%#= image_tag "heart.svg", class:"wishlistgift-image", data: {savegifts_target: "remove"}%>
    <%# end %>