config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }
  root to: "gifts#index"
  resources :events do
    resources :wishlistgifts, only: %i[index create show]
  end
  resources :wishlistgifts, only: %i[] do
    resources :votings, only: %i[create show]
  end
  resources :votings, only: %i[destroy]
  resources :chatrooms, only: %i[show index] do
    resources :messages, only: :create
  end
  resources :gifts
  get "/profile", to: "pages#profile"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :members
  has_many :users, through: :members
  has_many :event_tags
  has_many :wishlistgifts
  validates_numericality_of :price, :greater_than => 0
  validates :name, :start_time, :price, presence: true
  # validates :name, length: { minimum: 5, maximum: 15 }
  validates :photo, presence: true

  has_one_attached :photo
  acts_as_taggable_on :tags
  # acts_as_taggable_on :hobbies

  after_create :create_chatroom

  def create_chatroom
    Chatroom.create(name: name, event_id: id)
  end
end

# @event = Event.new(name: "test", start_time: "Wed, 30 Nov 2022 11:14:00.000000000 UTC +00:00", hobbies: "test", price: 100, photo: nil)
# @event.tag_list = "tag1, tag2"
# @event.save

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
    )
    @events = Event.joins(:members).where(user: current_user)
  end

  def show
    target_event = params[:id]
    price_range = params[:eventidprice].present? ? params[:eventidprice] : params[:eventidpriceprice]

    # @members = @event.members.where(event_id: @event.id).joins(:user)
    if target_event.present? && price_range.present?
    @event = Event.find(params[:id])
    # @gifts = Gift.where(category: @event.event_tags.pluck(:name))
    @gifts = Gift.where(category: JSON.parse(@event.hobbies).pluck("value"))
    @wishlistgift = Wishlistgift.where(event_id: @event.id, gift_id: @gifts)
    @event.price = price_range.to_i
    @event.save!

    @filtiergifts = @gifts.reject do |filtergift|
    filtergift.price > price_range.to_i
    end

    @gifts = @filtiergifts.reject do |gift|
      gift.wishlistgifts.any? do |wlg|
        @wishlistgift.include?(wlg)
      end
    end
    else

      @event = Event.find(params[:id])
      # @gifts = Gift.where(category: @event.event_tags.pluck(:name))
      @gifts =  Gift.where(category: JSON.parse(@event.hobbies).pluck("value"))
      @wishlistgift = Wishlistgift.where(event_id: @event.id, gift_id: @gifts)

      @filtiergifts = @gifts.reject do |filtergift|
        filtergift.price > @event.price
      end

        @gifts = @filtiergifts.reject do |gift|
        gift.wishlistgifts.any? do |wlg|
          @wishlistgift.include?(wlg)
        end
      end
    end
    @members = @event.members.where(event_id: @event.id).joins(:user).select(('DISTINCT user_id'))
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @tags = JSON.parse(params[:event][:hobbies])
    @tags.map do |tag|
      if tag["value"].present?
        EventTag.create(name: tag["value"], event_id: @event.id)
      else
        flash.notice = "Sorry we can't find any gifts in this pricerange"
      end
      # @event.tag_list.add(tag["value"])
    end

    if @event.save
      redirect_to event_path(@event)
      @member = Member.new(user_id: current_user.id, event_id: @event.id)
      @member.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def tag_list
    tags.map(&:name).join(",")
  end

  private

  def event_params
    params.require(:event).permit(:name, :members, :start_time, :price, :photo, :hobbies)
  end
end

app/views/events/index.html.erb
<%= render "shared/giftheader" %>
<%= render "shared/calendar" %>
<div class="container text-center">
  <%= link_to "Add event", new_event_path, class:"btn-giftit my-5" %>
</div>
  <h4 class="text-center">Upcoming events</h4>
 <div class="container text-center events-container bottom-pushup">
    <% @events.uniq.each do |event| %>
    <div class="event-container my-3">
      <%= image_tag "ellipse.svg" %>
      <%= link_to event_path(event) do  %>
        <%= event.name.capitalize %> on:   <%= event.start_time.strftime("%A, %d %b %Y") %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<%= render "shared/createevent" %>
<div class="container px-5" data-controller="addhobby">
  <%= simple_form_for(@event) do |f|  %>
    <div class="container d-flex justify-content-center my-4">
      <%= image_tag "event.jpg", class:"event-image" %>
    </div>
    <div data-controller="photo-preview">
      <%= image_tag "", data: {photo_preview_target: "img"}, id:"upload-image" %>
      <%= f.input :photo, as: :file, label: 'Upload a picture', input_html:{class:"foto-form hidden", data: {action: "photo-preview#change", photo_preview_target: "input"}}%>
    </div>
    <%= f.input :name, input_html: {class:  "event-input"}, label: "Event's name" %>
    <%= f.input :start_time, input_html: {class:  "event-input"},  label: "Date",  html5: true %>
    <%= f.input :hobbies, input_html: {class:  "event-input"}, label: "Interests", class:"customLook", input_html: { data: { addhobby_target: "addHobby", action: "change->addhobby#addTag" } } %>
    <%# <%= f.hint 'Choose: Technology, Chocolate, Food, Cooking, Running, Hiking, Perfume, Practical, Subscriptions, Wellness, Yoga, Wildcard' %>
    <%= f.input :price, input_html: {class:  "event-input"},  placeholder: 'Set max amount between 0-600' %>
    <div class="row bottom-pushup">
      <div class="text-center d-flex justify-content-center mt-3">
        <%= f.submit class: "btn-giftit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{@event.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_image, cl_image_path(@event.photo.key) if @event.photo.present? %>
<%# data-controller="savegifts" %>
<%# data-savegifts-target="save" %>
<%# data-action="click->savegifts#togglegifts" %>
<div class="d-flex justify-content-center flex-nowrap m-5">
  <div class="event w-75">
    <h1><%= @event.name %> </h1> <%#= link_to "Delete", delete_path(@event) %>
    <div class="container">
      <div class="center">
        <%= cl_image_tag @event.photo.key, height: 131, width: 131, crop: :fill, :radius => 50 %>
      </div>
    </div>
    <div class="" data-controller="savegifts">

      <div class="" data-controller="eventhobby">
        <p class="text-center"> <strong><%= @event.start_time.strftime("%A, %d %b %Y") %></strong></p>
        <div class="d-flex justify-content-between"> Hobbies: <i class="fa-solid fa-sort-down" data-action="click->eventhobby#displayHobby"></i></div>
        <div class="d-none" data-eventhobby-target="hobby">
          <% @event.hobbies.split.each do |tag| %>
            <div class="show-hobbies">
              <%= JSON.parse(tag).pluck("value").join("") %>
            </div>
          <% end %>
        </div>
        </p>
        <div class="d-flex justify-content-between wishlist"> Saved gifts (<%= @wishlistgift.size %>)
        <i class="fa-solid fa-sort-down" data-action="click->eventhobby#displaySaved"></i>

        </div>
        <div class="my-3 d-flex justify-content-center">
          <div class="d-none " data-eventhobby-target="saved">
            <%# Wishlist %>
            <div class="wishlist">
                <% @wishlistgift.each do |wishlist| %>
                <%# DATA CONTROLLER %>
                  <div class="wishlistgift-container">
                    <% vote = Voting.find_by(user: current_user, wishlistgift: wishlist) %>
                    <%= render "shared/starlink", vote: vote, wishlist: wishlist %>
                    <%= link_to event_wishlistgift_path(@event, wishlist) do %>
                      <div class="wishlist-item">
                        <%= image_tag wishlist.gift.photo %>
                        <div class="wishlist-text">
                          <p><%= wishlist.gift.name.first(20) %> </p>
                          <p class="wishlist-price">$<%= wishlist.gift.price.to_i %></p>
                          <%# SCORE %>
                          <%# <% @voting = Voting.find_by(user: current_user, wishlistgift: wishlist) %>
                          <%# <% @voting.user = current_user %>
                          <%#= @voting.user.count %>
                        </div>
                      </div>
                    <% end %>
                  </div>
                  <% end %>
              </div>
              <script src="https://cdn.jsdelivr.net/npm/canvas-confetti@1.5.1/dist/confetti.browser.min.js"></script>
              <script>
                document.getElementsByClassName("btn-giftit")[0].addEventListener("click", () => {
                confetti();
                });
                
              </script>
              <%# Gift It %>
              <div class="container text-center">
                <%= link_to "Gift It!", "#", class:"btn-giftit my-5" %>
              </div>
            </div>
         </div>

        <span> Members: </span>
            <div class="d-flex">
          <% @members.each do |member| %>
            <% if member == @members.last %>
             <span class="nowrap"><%= member.user.username %></span>
            <% else %>
               <span class="nowrap"><%= member.user.username %></span><p>,&#160;</p>
            <% end %>
          <% end %>
            </div>



        <div class="sharebtn d-flex p-1">
          <i class="fa-solid fa-share-nodes sendicon"></i>
          <div class="" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            &nbsp;Share
          </div>
        </div>

<!-- Modal -->
<div class="modal fade modalbackground" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header modalpopupheaderfield">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">invite a friend!</h1><i class="fa-regular fa-paper-plane"></i>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body modalpopupmainfield">
       <%= simple_form_for(User.new(), url: user_invitation_path) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs modalpopuplabel">
          <%= f.input :email, :include_blank => true, placeholder: "friends emailadress" %>
          <%= f.input :username, :include_blank => true, placeholder: "choose a username" %>
        </div>

        <div class="form-actions">
          <%= hidden_field_tag(:event, @event.id) %>
          <div class="" data-bs-dismiss="modal">
            <%= f.button :submit, t("devise.invitations.new.submit_button"),class:"modalsendbtn" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>


      <div data-controller="pricebutton">
        <label  data-pricebutton-target="number" for="temp">Price: <%= @event.price.to_i %>$</label><br />
<!--
        <input data-action="change->pricebutton#updateNumber" data-pricebutton-price-value=value data-pricebutton-target="price"  type="range" id="temp" name="temp" list="tickmarks" min="0" max="500" value="<%= @event.price %>" />
        <%= link_to "Update", event_path(@event, :eventid => @event.id), class: "btn btn-primary", data: {pricebutton_target: "button", action: "click->pricebutton#sendRequest"} %>
-->
        <input class="slider my-4", data-action="change->pricebutton#updateNumber" data-pricebutton-price-value=value data-pricebutton-target="price"  type="range" id="temp" name="temp" list="tickmarks" min="1" max="500" value="<%= @event.price %>" />
        <%= link_to "Update", event_path(@event, :eventid => @event.id), class: "btn-giftit-small", data: {pricebutton_target: "button", action: "click->pricebutton#sendRequest"} %>
      </div>

<!--
 <%= simple_form_for(@event) do |f|  %>
    <%= f.input :price, as: :range, input_html:{ min:"0", max:"500", data: {action: "change->pricebutton#updateTextInput(this.value)"}} %>
    <input type="text" id="textInput" value="">
    <%= f.submit class: "btn btn-primary" %>
 <% end %>
-->
<!--
  <label for="temp">Price: $<%= @event.price %></label><br />
 <%= simple_form_for @event do |f| %>
    <%= f.input :price, as: :range, input_html: { min: '0', step: 'any' }, label: "" %>
    <%= f.button :submit, class:"btn btn-primary" %>
<% end %>
   </div>
        <!--
        <input type="range" id="temp" name="temp" list="tickmarks" value="<%= @event.price %>" />
-->
        <h3 class="my-4"> Gift Suggestions</h3>
        <div class="wishlist bottom-pushup">
          <% @gifts.each do |gift| %>
            <div class="wishlistgift-container">
              <%= link_to event_wishlistgifts_path(@event, :gift_params => gift.id), data: {turbo_method: :post, action: "click->savegifts#disconnect"} do %>
                <%= image_tag "heart.svg", class:"wishlistgift-image", data: {savegifts_target: "remove"}%>
              <% end %>
              <%= link_to gift_path(gift) do %>
                <div class="wishlist-item">
                  <%= image_tag gift.photo %>
                  <div class="wishlist-text">
                    <p><%= gift.name.first(20) %></p>
                    <p class="wishlist-price">$<%= gift.price.to_i %> </p>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>